### ISSUE TITLE
Does not work on wayland

### ISSUE THREAD

**Issue by MimzyFang** [LitnhJacuzzi/CursorCentered-Fix#4]
did not expect it to work on wayland due to the error message I usualy get but you might want to add that as a disclaimer to your mod's description

```
[17:24:55] [Render thread/ERROR]: ########## GL ERROR ##########
[17:24:55] [Render thread/ERROR]: @ Render
[17:24:55] [Render thread/ERROR]: 65548: Wayland: The platform does not support setting the cursor position
```

**Comment by LitnhJacuzzi** [comment]
Do you still get this error after only uninstalling this mod? The error log you've provided is about a GL problem and this mod is actually not relevant with rendering code(see #2 for details), so I think it's should not be caused by this mod. Cursor centering code is provided by Minecraft instead of this mod, it seems that if you uninstall this mod the error will still appear.

**Comment by MimzyFang** [comment]
> Do you still get this error after only uninstalling this mod? The error log you've provided is about a GL problem and this mod is actually not relevant with rendering code(see #2 for details), so I think it's should not be caused by this mod. Cursor centering code is provided by Minecraft instead of this mod, it seems that if you uninstall this mod the error will still appear.

Yes it does was hoping this mod could fix it but I didn't really expect it
 It's a Wayland specific issue that probably needs a protocol extension or support from LWJGL not sure rn
The point of this issue is to maybe add some information to the readme to inform people that this is not about the Wayland issue

**Comment by LitnhJacuzzi** [comment]
OK, I can almostly confirm it's a LWJGL issue as I inferred. In this case, you should have noticed the cursor cannot be centered **all the time**, and to fix it we need to replace the original cursor centering implementation provided by Minecraft, which is beyond the current purpose(fixing [MC-150164](https://bugs.mojang.com/browse/MC-150164)) of this mod and will be an "additional feature" if I add it.

I'm not sure whether LWJGL has provided cursor centering method for Wayland platform, and it will be a little difficult if it doesn't. However, this feature looks valuable so I'll try to implement it.

**Comment by LitnhJacuzzi** [comment]
I've fonud some confused problems when I first playing Minecraft under Wayland just now, there was only one of all cursor-related operations took effect - locking operation(hides the cursor makes all mouse inputs redirect to the game window), I couldn't even control the facing direction using the mouse. The cursor was able to move after locking and can't be centered all the time as I expected before.

Since I'm using Wayland in a virtual machine, this phenomenon may be casued by the compatibility of VM driver. If these issues are also existed in your environment, it means the problem has become much more complicated than previous estimation - the current versions of Minecraft are nearly **NOT** provide mouse compatibility for Wayland platform, and in this case we need to rewrite almost the whole mouse input system of Minecraft to make it compatible with Wayland.

If the assumption above established, I won't continue to develop this feature in this mod because it's not a work of fixing bugs but a work of adding new functions(and will be named as "Wayland Mouse Support Mod" if implemented). And if you are also unable to control the camera using mouse, I'd like to suggest playing on another platform before Minecraft has supported Wayland officially.

**Comment by MimzyFang** [comment]
I personally can control the game just fine just the curser is not locked to the center but wherever it was on the screen when going back to the game though I really don't want you to waste more time into this so I'm going to close this issue

**Comment by LitnhJacuzzi** [comment]
I see. This issue does have many factors due to the compatibilities of Wayland platform. It *will* be a challenging task since GLFW itself has some critical problems on Wayland. Maybe it's not the best time to handle this issue right now.

As for the mod description, I describe the function of this mod as "fixes the centering issue that *occasionally* happens when..." so it should not be expected to solve something like "the centering issue that *permanently* happens", because it obviously implies another major bug.

**Comment by ShayBox** [comment]
Dang, I thought this mod would help with this annoying bug, but I guess not. The game normally resets the mouse position, but if you open an inventory, move your mouse, close it, and open it again without moving your mouse in-game it won't reset, but if you move your mouse in-game it'll reset.

**Comment by LitnhJacuzzi** [comment]
This feature has temporarily implemented since I accidentally noticed an [automation tool](https://github.com/ReimuNotMoe/ydotool) on wayland, I'd like to know if the current centering latency is acceptable for you.
